import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/custom/Header/Header";
import Footer from "@/components/custom/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import localfont from 'next/font/local'

const myFont = localfont({
      src: [
        {
        path: "../../public/fonts/Rumburak.ttf",
        weight: "700",
        }
      ], 
      variable: "--font-myFont",
  });


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${myFont.variable}`}>

      <body className={inter.className}>
      <Header/>
      <div className="mt-24">
        {children}
      </div>
      <Footer/>
      </body>
    </html>
  );
}
